// This file is automatically generated by the Firebase setup process.
// Do not manually edit this file.

// The following configuration object is for a public Firebase project.
// It is safe to expose this configuration in your client-side code.
// Security is handled by Firestore Security Rules and not by keeping
// this configuration private.
export const firebaseConfig = {
  projectId: 'alexa-0-1-ayer',
  appId: '1:448893645226:web:9889f572ef172d9fd43bd3',
  apiKey: 'AIzaSyB5xlWKM32H9dlKczXI97rQeQ7tqx1vCno',
  authDomain: 'alexa-0-1-ayer.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '448893645226',
  storageBucket: 'alexa-0-1-ayer.appspot.com',
};
