// This file is automatically generated by the Firebase setup process.
// Do not manually edit this file.

// The following configuration object is for a public Firebase project.
// It is safe to expose this configuration in your client-side code.
// Security is handled by Firestore Security Rules and not by keeping
// this configuration private.
export const firebaseConfig = {
  "apiKey": "from-default-project",
  "authDomain": "from-default-project",
  "projectId": "from-default-project",
  "storageBucket": "from-default-project",
  "messagingSenderId": "from-default-project",
  "appId": "from-default-project"
};
