// This file is automatically generated by the Firebase setup process.
// Do not manually edit this file.

// The following configuration object is for a public Firebase project.
// It is safe to expose this configuration in your client-side code.
// Security is handled by Firestore Security Rules and not by keeping
// this configuration private.
export const firebaseConfig = {
  apiKey: "AIzaSyC2qjF4tZ-redacted-83dZ1i3c",
  authDomain: "alexa-0-1-ayer.firebaseapp.com",
  projectId: "alexa-0-1-ayer",
  storageBucket: "alexa-0-1-ayer.appspot.com",
  messagingSenderId: "1",
  appId: "1:1:web:1",
};
